### ISSUE TITLE
K8s or docker

### ISSUE THREAD

**Issue by RepairYourTech** [tjmlabs/AgentRun#15]
I would like to add this to my kubernetes as a service for my flowise and n8n apps, part of my stack. Is there a docker image I can use?

**Comment by Jonathan-Adly** [comment]
Hey - the API is docker-compose project, so it can work with minimal adjustment in your setup, you can build/push the Dockerfiles in the repo and use that as is.

1. Clone the repo and cd to agentrun-api 

2. Build and push both images to a container registry (Docker Hub):
```
# Build images
docker build -f docker/api/Dockerfile -t your-registry/agentrun-api:latest .
docker build -f docker/code_runner/Dockerfile -t your-registry/python-runner:latest .
```
```
# Push images
docker push your-registry/agentrun-api:latest
docker push your-registry/python-runner:latest
```

The docker-compose maps a volume, and takes care of networking. For Kubernetes, it will be naturally different. You will probably need:
- A Kubernetes Service for the API
- Deployments for both containers
- A PersistentVolume/PersistentVolumeClaim for the code execution volume

I don't know enough about K8s beyond that. Big picture, AgentRun just takes a running a container and makes it into a sandbox. So, really any running container will do.
