### ISSUE TITLE
Unable to configure local LLM

### ISSUE THREAD

**Issue by 16x3b** [tjmlabs/AgentRun#2]
In the documentation you mention litellm, but you only give examples for groq and openAI. I'd like to use both LM_studio or Ollama, but would settle for understanding how to integrate litellm. 

Thank you for taking the time to code this!

**Comment by Jonathan-Adly** [comment]
Hey there!

I have added an Ollama Example: https://jonathan-adly.github.io/AgentRun/examples/ollama_llama3/

Closing this issue!
